parser: "@typescript-eslint/parser"
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - plugin:import/recommended
  - plugin:import/typescript
settings:
  import/resolver:
    typescript: true
  import/core-modules:
    - bun:sqlite
    - bun:test
rules:
  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
        - parent
        - sibling
        - index
        - object
        - type
      alphabetize:
        order: asc
        caseInsensitive: true
      pathGroups:
        - pattern: "@/**"
          group: internal
          position: before
